Raspberry-Pi-Camera-part-for-Drogerdy-Tank-Bot-componentRack.stl:
  hash: 743b4c3d74abe63fcbaa7edb184592e852f52c28
  links: []
  notes: []
Raspberry-Pi-Camera-part-for-Drogerdy-Tank-Bot-piCamBody.stl:
  hash: 44be506f60687ca3458eb03a36027845ccf15f31
  links: []
  notes: []
