1._Nose_(repaired).gco:
  analysis:
    dimensions:
      depth: 77.73899999999999
      height: 114.4
      width: 92.84
    estimatedPrintTime: 10213.957615551362
    filament:
      tool0:
        length: 10192.805160000245
        volume: 0.0
    printingArea:
      maxX: 138.954
      maxY: 129.79
      maxZ: 114.7
      minX: 46.114
      minY: 52.051
      minZ: 0.3
  hash: 366594dba2e69ec9bd06ca5e04031a5b01ad2b8e
  history:
  - printTime: 14036.308166980743
    printerProfile: _default
    success: true
    timestamp: 1504766599.085695
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 14036.308166980743
    lastPrintTime:
      _default: 14036.308166980743
1._Nose_(repaired).stl:
  hash: d6246b5ac52953569495fc9b60c42270c0969e08
  links: []
  notes: []
10._Spitfire_Middle_Body_-_Tail1.gco:
  analysis:
    dimensions:
      depth: 68.102
      height: 82.8
      width: 40.419
    estimatedPrintTime: 3619.0119593176187
    filament:
      tool0:
        length: 3534.9146600000013
        volume: 0.0
    printingArea:
      maxX: 112.74
      maxY: 126.555
      maxZ: 83.1
      minX: 72.321
      minY: 58.453
      minZ: 0.3
  hash: b1a049aabbde9dfc8b1a0622015c79548217eb1f
  history:
  - printTime: 5597.840672016144
    printerProfile: _default
    success: true
    timestamp: 1505005593.802038
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 5597.840672016144
    lastPrintTime:
      _default: 5597.840672016144
10._Spitfire_Middle_Body_-_Tail1.stl:
  hash: c81006dda91109dc1097f77272c903d64f4f25ce
  links: []
  notes: []
11._Spitfire_Right_Wing_Part_A_(repaired).gco:
  analysis:
    dimensions:
      depth: 16.256
      height: 55.6
      width: 82.272
    estimatedPrintTime: 3109.495509141374
    filament:
      tool0:
        length: 2925.9677900000033
        volume: 0.0
    printingArea:
      maxX: 134.352
      maxY: 101.187
      maxZ: 55.9
      minX: 52.08
      minY: 84.931
      minZ: 0.3
  hash: 347db668e2b56c693c5cd2eb81c792e881371bfa
  history:
  - printTime: 4616.59250497818
    printerProfile: _default
    success: true
    timestamp: 1505012444.782647
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 4616.59250497818
    lastPrintTime:
      _default: 4616.59250497818
11._Spitfire_Right_Wing_Part_A_(repaired).stl:
  hash: 17a720a6170122dec16656aa1a471b20ff5e2873
  links: []
  notes: []
12._Spitfire_Right_Wing_Part_B.STL:
  hash: e4c1f6db9dddb3affc0708318b483081c825f77a
  links: []
  notes: []
12._Spitfire_Right_Wing_Part_B.gco:
  analysis:
    dimensions:
      depth: 25.819999999999993
      height: 120.8
      width: 124.96000000000001
    estimatedPrintTime: 6964.552439899042
    filament:
      tool0:
        length: 8011.626810000098
        volume: 0.0
    printingArea:
      maxX: 155.655
      maxY: 107.381
      maxZ: 121.1
      minX: 30.695
      minY: 81.561
      minZ: 0.3
  hash: 245b3162a0629a56e0862a41c0d09a56de69ab85
  history:
  - printTime: 8984.874762058258
    printerProfile: _default
    success: true
    timestamp: 1505023923.220097
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 8984.874762058258
    lastPrintTime:
      _default: 8984.874762058258
13._Spitfire_Right_Wing_Part_C.STL:
  hash: db841f26a4c792fcf28b476b92ff295d0f0e6dde
  links: []
  notes: []
13._Spitfire_Right_Wing_Part_C.gco:
  analysis:
    dimensions:
      depth: 40.82900000000001
      height: 81.0
      width: 133.44
    estimatedPrintTime: 10342.741328385828
    filament:
      tool0:
        length: 8865.73613000001
        volume: 0.0
    printingArea:
      maxX: 159.856
      maxY: 114.897
      maxZ: 81.3
      minX: 26.416
      minY: 74.068
      minZ: 0.3
  hash: c3d675d5def54a72cefe0aeca22e6917aa99baaf
  history:
  - printerProfile: _default
    success: false
    timestamp: 1505080669.37583
  - printTime: 14313.212960004807
    printerProfile: _default
    success: true
    timestamp: 1505095037.948031
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 14313.212960004807
    lastPrintTime:
      _default: 14313.212960004807
14._Spitfire_Control_Surface_4_1.gco:
  analysis:
    estimatedPrintTime: 1727
    filament:
      tool0:
        length: 1526
        volume: 3.670460141867549
      tool1:
        length: 0
        volume: 0.0
  hash: 2cd001672a61833471db1d23b8263b98b4ba2489
  history:
  - printTime: 1794.759479045868
    printerProfile: _default
    success: true
    timestamp: 1505184401.139327
  statistics:
    averagePrintTime:
      _default: 1794.759479045868
    lastPrintTime:
      _default: 1794.759479045868
14._Spitfire_Control_Surface_4_1.stl:
  hash: ad3851f310ac98f989be20299af76f743742ab35
  links: []
  notes: []
14._Spitfire_Control_Surface_4_2.gco:
  analysis:
    dimensions:
      depth: 10.58999999999999
      height: 13.399999999999999
      width: 165.266
    estimatedPrintTime: 1422.069069494804
    filament:
      tool0:
        length: 1236.63385
        volume: 0.0
    printingArea:
      maxX: 175.146
      maxY: 97.82
      maxZ: 13.7
      minX: 9.88
      minY: 87.23
      minZ: 0.3
  hash: f1c3d6130017c84165211d9ec0970fcc70edcb1c
  links: []
  notes: []
14._Spitfire_Control_Surface_4_2.stl:
  hash: 448fbaa5ce97d0e867014957c32faf70f0f2430b
  links: []
  notes: []
15._Spitfire_Middle_Body_-_Tail2_bot.gco:
  analysis:
    estimatedPrintTime: 12485
    filament:
      tool0:
        length: 9196
        volume: 22.118972126221486
      tool1:
        length: 0
        volume: 0.0
  hash: 0b82504cc8537d261dcec7a5577351b7a61f53c1
  history:
  - printTime: 13762.546946048737
    printerProfile: _default
    success: true
    timestamp: 1505226373.321103
  statistics:
    averagePrintTime:
      _default: 13762.546946048737
    lastPrintTime:
      _default: 13762.546946048737
15._Spitfire_Middle_Body_-_Tail2_bot.stl:
  hash: 0e6a2786e7e95780e8f32b509e60c7c73a65cc19
  links: []
  notes: []
15._Spitfire_Middle_Body_-_Tail2_top.gco:
  analysis:
    dimensions:
      depth: 86.80999999999999
      height: 38.6
      width: 148.214
    estimatedPrintTime: 9012.334891350205
    filament:
      tool0:
        length: 7348.304010000165
        volume: 0.0
    printingArea:
      maxX: 166.56
      maxY: 133.914
      maxZ: 38.9
      minX: 18.346
      minY: 47.104
      minZ: 0.3
  hash: d4a6824e4f520270e15e9ffbdcd081d78c0c68a3
  links: []
  notes: []
15._Spitfire_Middle_Body_-_Tail2_top.stl:
  hash: cf01a5d6335b8f40600bd9445d2176181420d3a4
  links: []
  notes: []
16._Spitfire_spitfire_control_surface_1_1.gco:
  analysis:
    dimensions:
      depth: 11.745999999999995
      height: 8.6
      width: 105.607
    estimatedPrintTime: 984.9929589944941
    filament:
      tool0:
        length: 953.3396299999998
        volume: 0.0
    printingArea:
      maxX: 144.588
      maxY: 98.969
      maxZ: 8.9
      minX: 38.981
      minY: 87.223
      minZ: 0.3
  hash: bf853688886aa7eabe226fa5e5d833331a0524ab
  history:
  - printTime: 1677.5186381340027
    printerProfile: _default
    success: true
    timestamp: 1505262093.151438
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 1677.5186381340027
    lastPrintTime:
      _default: 1677.5186381340027
16._Spitfire_spitfire_control_surface_1_1.stl:
  hash: 7f56da55e22820d6979eb4da4cb3fe39e8cc80bc
  links: []
  notes: []
16._Spitfire_spitfire_control_surface_1_2.gco:
  analysis:
    dimensions:
      depth: 11.650000000000006
      height: 14.2
      width: 105.6
    estimatedPrintTime: 780.5145267811315
    filament:
      tool0:
        length: 682.2020300000004
        volume: 0.0
    printingArea:
      maxX: 146.813
      maxY: 98.299
      maxZ: 14.5
      minX: 41.213
      minY: 86.649
      minZ: 0.3
  hash: aad39b43088dffa89f4455183db64ecd75ece6e9
  history:
  - printTime: 1332.290915966034
    printerProfile: _default
    success: true
    timestamp: 1505269997.690847
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 1332.290915966034
    lastPrintTime:
      _default: 1332.290915966034
16._Spitfire_spitfire_control_surface_1_2.stl:
  hash: 708ea0e2884385a95966880c2d602c4eb4abc5d3
  links: []
  notes: []
16._Spitfire_spitfire_control_surface_2_1.gco:
  analysis:
    dimensions:
      depth: 11.719999999999999
      height: 8.6
      width: 105.83099999999999
    estimatedPrintTime: 991.6184959165245
    filament:
      tool0:
        length: 945.6719799999996
        volume: 0.0
    printingArea:
      maxX: 144.73
      maxY: 97.704
      maxZ: 8.9
      minX: 38.899
      minY: 85.984
      minZ: 0.3
  hash: b4251cd6305464a50b5e5206ae563ec3db46cc61
  history:
  - printTime: 1695.2780799865723
    printerProfile: _default
    success: true
    timestamp: 1505321180.187401
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 1695.2780799865723
    lastPrintTime:
      _default: 1695.2780799865723
16._Spitfire_spitfire_control_surface_2_1.stl:
  hash: 94a1605ce2ef3d28122080f3a880bfd22dfdbc72
  links: []
  notes: []
16._Spitfire_spitfire_control_surface_2_2.gco:
  analysis:
    dimensions:
      depth: 11.623999999999995
      height: 14.0
      width: 105.82000000000001
    estimatedPrintTime: 778.6058094726188
    filament:
      tool0:
        length: 682.9884799999998
        volume: 0.0
    printingArea:
      maxX: 146.859
      maxY: 98.338
      maxZ: 14.3
      minX: 41.039
      minY: 86.714
      minZ: 0.3
  hash: f1fb60ea222a145f0bc5118d2ddd0efe41c2d93f
  history:
  - printTime: 1311.4327778816223
    printerProfile: _default
    success: true
    timestamp: 1505323493.560381
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 1311.4327778816223
    lastPrintTime:
      _default: 1311.4327778816223
16._Spitfire_spitfire_control_surface_2_2.stl:
  hash: 41acad9da737f2c449e75491b0ae44e0c5099e09
  links: []
  notes: []
17._Spitfire_Control_Surface_3.gco:
  analysis:
    dimensions:
      depth: 98.555
      height: 31.4
      width: 15.759999999999991
    estimatedPrintTime: 2393.861481072926
    filament:
      tool0:
        length: 2263.4129800000023
        volume: 0.0
    printingArea:
      maxX: 100.38
      maxY: 141.785
      maxZ: 31.7
      minX: 84.62
      minY: 43.23
      minZ: 0.3
  hash: 469de7c54096158f1687f7e2c6cbe11166e77123
  history:
  - printTime: 3504.8999750614166
    printerProfile: _default
    success: true
    timestamp: 1505327250.432184
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 3504.8999750614166
    lastPrintTime:
      _default: 3504.8999750614166
17._Spitfire_Control_Surface_3.stl:
  hash: 6500f3b6afc97cc48952e621d0dcb4b839a8b9c1
  links: []
  notes: []
2._Nose_tip_(repaired).gco:
  analysis:
    dimensions:
      depth: 60.768
      height: 20.0
      width: 50.708
    estimatedPrintTime: 2233.012517927788
    filament:
      tool0:
        length: 2242.375990000002
        volume: 0.0
    printingArea:
      maxX: 117.834
      maxY: 122.863
      maxZ: 20.3
      minX: 67.126
      minY: 62.095
      minZ: 0.3
  hash: a362c7ae572411ea9412ddf7e640ca249a1cd7b2
  history:
  - printTime: 3519.7902660369873
    printerProfile: _default
    success: true
    timestamp: 1504783383.810983
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 3519.7902660369873
    lastPrintTime:
      _default: 3519.7902660369873
2._Nose_tip_(repaired).stl:
  hash: c68efc403e177cde18361c7efccbf0b627909e1f
  links: []
  notes: []
3._Spitfire_final_middle_body_-_bottom1_(repaired).gco:
  analysis:
    dimensions:
      depth: 53.19799999999999
      height: 99.60000000000001
      width: 92.84
    estimatedPrintTime: 8481.128795714047
    filament:
      tool0:
        length: 7579.214550000073
        volume: 0.0
    printingArea:
      maxX: 138.919
      maxY: 118.017
      maxZ: 99.9
      minX: 46.079
      minY: 64.819
      minZ: 0.3
  hash: d135c3a8d465686656cfc49b079115a5b951ad35
  history:
  - printerProfile: _default
    success: false
    timestamp: 1504799844.20405
  - printTime: 11365.016410112381
    printerProfile: _default
    success: true
    timestamp: 1504814682.681122
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 11365.016410112381
    lastPrintTime:
      _default: 11365.016410112381
3._Spitfire_final_middle_body_-_bottom1_(repaired).stl:
  hash: 574f5cb2f918e5b45684f018aaf9515b9e0df2d5
  links: []
  notes: []
4._Spitfire_final_middle_body_-_bottom2_(repaired).gco:
  analysis:
    dimensions:
      depth: 40.211
      height: 74.8
      width: 42.931
    estimatedPrintTime: 3124.6244365904417
    filament:
      tool0:
        length: 3368.188650000002
        volume: 0.0
    printingArea:
      maxX: 113.964
      maxY: 110.608
      maxZ: 75.1
      minX: 71.033
      minY: 70.397
      minZ: 0.3
  hash: 16e892d005271727ed0baf40d6a07f3afdca0186
  history:
  - printTime: 4319.518637180328
    printerProfile: _default
    success: true
    timestamp: 1504823528.551074
  - printTime: 4331.556292057037
    printerProfile: _default
    success: true
    timestamp: 1504836481.332054
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 4325.537464618683
    lastPrintTime:
      _default: 4331.556292057037
4._Spitfire_final_middle_body_-_bottom2_(repaired).stl:
  hash: e2b696d6f8071435a855ffa97efeb97f5cca5a1f
  links: []
  notes: []
5._Spitfire_final_middle_body_-_Top2_(repaired).gco:
  analysis:
    dimensions:
      depth: 42.367000000000004
      height: 95.0
      width: 42.845
    estimatedPrintTime: 2707.142735176057
    filament:
      tool0:
        length: 2925.615910000001
        volume: 0.0
    printingArea:
      maxX: 113.922
      maxY: 115.711
      maxZ: 95.3
      minX: 71.077
      minY: 73.344
      minZ: 0.3
  hash: 549c4590b9e3da7b86fdf74c37a8cb6664bf9ac0
  history:
  - printTime: 3722.7325160503387
    printerProfile: _default
    success: true
    timestamp: 1504840302.272723
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 3722.7325160503387
    lastPrintTime:
      _default: 3722.7325160503387
5._Spitfire_final_middle_body_-_Top2_(repaired).stl:
  hash: 88320bb254ebb645d206c1590c12d8ecc458d48f
  links: []
  notes: []
6._Spitfire_final_middle_body_-_Top1.STL:
  hash: 2d77116d30e464190396a090f7a26879bdfa82b9
  links: []
  notes: []
6._Spitfire_final_middle_body_-_Top1.gco:
  analysis:
    dimensions:
      depth: 47.245000000000005
      height: 79.4
      width: 50.913
    estimatedPrintTime: 6909.368419520521
    filament:
      tool0:
        length: 5968.981160000124
        volume: 0.0
    printingArea:
      maxX: 117.959
      maxY: 118.128
      maxZ: 79.7
      minX: 67.046
      minY: 70.883
      minZ: 0.3
  hash: 115de0fb6d552b3b73f35b2d1f0792c64e07246a
  history:
  - printTime: 10871.875776052475
    printerProfile: _default
    success: true
    timestamp: 1504880926.724275
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 10871.875776052475
    lastPrintTime:
      _default: 10871.875776052475
7._Spitfire_Left_Wing_Part_A_(repaired).gco:
  analysis:
    dimensions:
      depth: 16.245999999999995
      height: 55.6
      width: 82.264
    estimatedPrintTime: 3120.950653968796
    filament:
      tool0:
        length: 2924.6276900000025
        volume: 0.0
    printingArea:
      maxX: 134.345
      maxY: 100.092
      maxZ: 55.9
      minX: 52.081
      minY: 83.846
      minZ: 0.3
  hash: 0824f89db701c1f8e50969016a44b10ee3b47abc
  history:
  - printTime: 4605.404542922974
    printerProfile: _default
    success: true
    timestamp: 1504911185.056615
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 4605.404542922974
    lastPrintTime:
      _default: 4605.404542922974
7._Spitfire_Left_Wing_Part_A_(repaired).stl:
  hash: 18cd95d5228a1f9d914025eae93c25d83e31dc8a
  links: []
  notes: []
8._Spitfire_Left_Wing_Part_B_(repaired).gco:
  analysis:
    dimensions:
      depth: 25.822000000000003
      height: 120.8
      width: 124.967
    estimatedPrintTime: 6994.16065801071
    filament:
      tool0:
        length: 8009.078740000189
        volume: 0.0
    printingArea:
      maxX: 155.66
      maxY: 103.441
      maxZ: 121.1
      minX: 30.693
      minY: 77.619
      minZ: 0.3
  hash: a376a7950b59a1a31197c5adfcddf9ad74040243
  history:
  - printTime: 14460.788490056992
    printerProfile: _default
    success: true
    timestamp: 1504930537.806047
  - printTime: 9115.170412063599
    printerProfile: _default
    success: true
    timestamp: 1504980620.301842
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 11787.979451060295
    lastPrintTime:
      _default: 9115.170412063599
8._Spitfire_Left_Wing_Part_B_(repaired).stl:
  hash: 12d4044120526c45f21a2d9e476b59fa2bdb2a2a
  links: []
  notes: []
9._Spitfire_Left_Wing_Part_C.gco:
  analysis:
    dimensions:
      depth: 40.833
      height: 81.0
      width: 133.452
    estimatedPrintTime: 10225.143058481093
    filament:
      tool0:
        length: 8805.188739999914
        volume: 0.0
    printingArea:
      maxX: 159.87
      maxY: 110.931
      maxZ: 81.3
      minX: 26.418
      minY: 70.098
      minZ: 0.3
  hash: 413c63c71cefbac6d8294b6c548903391d0be5c4
  history:
  - printTime: 14279.08484005928
    printerProfile: _default
    success: true
    timestamp: 1504946061.33699
  - printTime: 14313.568268060684
    printerProfile: _default
    success: true
    timestamp: 1505115282.191101
  links: []
  notes: []
  statistics:
    averagePrintTime:
      _default: 14296.326554059982
    lastPrintTime:
      _default: 14313.568268060684
9._Spitfire_Left_Wing_Part_C.stl:
  hash: 6d1372a9c0d6beb1b28751daa58782f59193fec4
  links: []
  notes: []
Full_Spitfire_example_(repaired).stl:
  hash: dba55f69e11fefdebc459b86a783e913a35ef680
  links: []
  notes: []
