3DBenchy.stl:
  hash: c240f46ca3f38c6c8d61b6f4247898577231af18
  links: []
  notes: []
3DBenchy_-_Dualprint_-_Gunwale_Deck_Plate_Wheel_Frames_Roof_Chimney_top_-_3DBenchy.com.stl:
  hash: 3f27df5ee05303f98b95ca208780511faf986064
  links: []
  notes: []
3DBenchy_-_Dualprint_-_Hull_Box_Bridge_walls_Rod-holder_Chimney_-_3DBenchy.com.stl:
  hash: 90d25e8dae309c5fb889b3c6af23bb516d309179
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Complete_17_shells_-_3DBenchy.com.stl:
  hash: 45d12c03baff1239cec660232282488c921f11a6
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Bridge_roof_-_3DBenchy.com.stl:
  hash: 463b4275a5c919c6a5ca1df2bd87fdb3f0e34b0a
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Bridge_walls_-_3DBenchy.com.stl:
  hash: 62997444c89653231f217a6cda92bff4a393bddc
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Cargo_box_-_3DBenchy.com.stl:
  hash: 043a5a6967c144c3e5495cec1538449769e8c3d3
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Chimney_body_-_3DBenchy.com.stl:
  hash: 4f11502897e54e01b352a4ab06ed7fb63ff36046
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Chimney_top_-_3DBenchy.com.stl:
  hash: 7a79e9f374a30836d474e74f6006d18306187a5e
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Deck_surface_-_3DBenchy.com.stl:
  hash: abd132cdd82e7ce306f2419e45251fb8d073167d
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Doorframe_port_-_3DBenchy.com.stl:
  hash: a451e178dd3aef99ffcce25fe5e78466fc5c4679
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Doorframe_starboard_-_3DBenchy.com.stl:
  hash: d287628b64b2b3b630ed88afbbaf080b15d845c1
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Fishing-rod-holder_-_3DBenchy.com.stl:
  hash: 20d9ecd31bed9df8ea12818f86d2e5690523412e
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Gunwale_-_3DBenchy.com.stl:
  hash: 5121ca1995e40359bca0d6d456ffc9b133df9d9f
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Hawsepipe_port_-_3DBenchy.com.stl:
  hash: 8a1de15aa1051316f356149b4a5bb189c4ecab0b
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Hawsepipe_starboard_-_3DBenchy.com.stl:
  hash: 06f47ff9fac0732f9ea2745cd03ee5fa687f4391
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Hull_-_3DBenchy.com.stl:
  hash: 0060a011998bff1d71eb1cb018ad5d4b08020188
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Stern_name_plate_-_3DBenchy.com.stl:
  hash: d1ca0fc821ed9bd18d0ab1d42a86008eb0ad0f7e
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Stern_window_-_3DBenchy.com.stl:
  hash: 23734712b01664e1f7dc7b77064505bbd0416ab7
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Wheel_-_3DBenchy.com.stl:
  hash: 7710098f875f27ab67fd2d9f04914841d16daabc
  links: []
  notes: []
3DBenchy_-_Multi-part_-_Single_-_Window_-_3DBenchy.com.stl:
  hash: b4141a829ae178165e481022e702c9cb84624224
  links: []
  notes: []
