tengu-august-rev-2-batteryhatch-part1-2.stl:
  hash: 83fc16292c5c44d877b615f80807e5e9b47eb883
  links: []
  notes: []
tengu-august-rev-2-batteryhatch-part2-5.stl:
  hash: 850f8f08c18406c2bd5f964e3aba9746c2ce6597
  links: []
  notes: []
tengu-august-rev-2-batteryhatch-part2-6.stl:
  hash: 4e387782c7d0f83d6b086122aad5c1e664d3481a
  links: []
  notes: []
tengu-august-rev-2-camera-fairing.stl:
  hash: 3798803d1b48a19d8a3f74bbe2596de3f45bc85b
  links: []
  notes: []
tengu-august-rev-2-drone-body-motor-cover-3.stl:
  hash: 0995763c8fa9a349401e7f89777c6eb308918409
  links: []
  notes: []
tengu-august-rev-2-flap-left-1.stl:
  hash: 90c668e2c39e04f00b5fbc0bd97a4cc55f717e2e
  links: []
  notes: []
tengu-august-rev-2-flap-left-2.stl:
  hash: b6226788d826dc2c4d2168d8ac43fe6f364a38b8
  links: []
  notes: []
tengu-august-rev-2-flap-right-1.stl:
  hash: 50c0c1af6b59942b87feb98cba126cfa690616d6
  links: []
  notes: []
tengu-august-rev-2-flap-right-2.stl:
  hash: 29452e9107437c983a45e95230f8cc227357b7c0
  links: []
  notes: []
tengu-august-rev-2-fuse-pt-1-nose.stl:
  hash: 3d1ad863a9a2333375026a19969ee5121fe14d2e
  links: []
  notes: []
tengu-august-rev-2-fuse-pt-2-battery-section.stl:
  hash: dbebfc23441bf680f13c901ac5ef85df36532df7
  links: []
  notes: []
tengu-august-rev-2-fuse-pt-3-equipment-bay.stl:
  hash: b81f032d5405219f083326fc74904aed9c95af6c
  links: []
  notes: []
tengu-august-rev-2-fuse-pt-4-motor-housing.stl:
  hash: 424ed3e8842f15bd74b3e904e09188eaf040581e
  links: []
  notes: []
tengu-august-rev-2-l-wing-1.stl:
  hash: 46a325c008de5c4307f0c64e5a4ba4f924d4afc5
  links: []
  notes: []
tengu-august-rev-2-l-wing-vertical-tip.stl:
  hash: c8d795586d25d781608cf9488ea88a66d66f4bd2
  links: []
  notes: []
tengu-august-rev-2-part-26.stl:
  hash: 7bc1e7965802bc09a1aaddd9479b176cc8f0b5b5
  links: []
  notes: []
tengu-august-rev-2-part-27.stl:
  hash: d176404540d68c58574a47af6e86a595b8ab2b80
  links: []
  notes: []
tengu-august-rev-2-part-28.stl:
  hash: ee08752acbbc1fcf334e1358af8cf56c0bc2db50
  links: []
  notes: []
tengu-august-rev-2-part-29.stl:
  hash: 82867a417d3bb569d56c9dd189ae2cffa7a79349
  links: []
  notes: []
tengu-august-rev-2-part-30.stl:
  hash: 85430467889c04f12b10f4709cf5be491af03efd
  links: []
  notes: []
tengu-august-rev-2-part-35.stl:
  hash: 21f19ac07d4c053eb2b5f2243b2587a68fcade7d
  links: []
  notes: []
tengu-august-rev-2-part-36.stl:
  hash: 3850b03a13365eadc3f96ea59c55bd6eefc04a9e
  links: []
  notes: []
tengu-august-rev-2-part-37.stl:
  hash: ec3cf067168be66446f53442f528cd2d024969d2
  links: []
  notes: []
tengu-august-rev-2-part-38.stl:
  hash: cb467e98dd8d0b953b0db59339533e8a5a166945
  links: []
  notes: []
tengu-august-rev-2-part-39.stl:
  hash: 7b050bf7fd18848b743c28c3f4294ec4eb144b9b
  links: []
  notes: []
tengu-august-rev-2-part-40.stl:
  hash: 53bafd6265cd0aef916741126f5357a16c0ff622
  links: []
  notes: []
tengu-august-rev-2-part-41.stl:
  hash: 83fcaf7de8e586df239f4e523b497d1bbf2b2892
  links: []
  notes: []
tengu-august-rev-2-part-42.stl:
  hash: f540aada110957aab48ccf0f4610f0065067eea2
  links: []
  notes: []
tengu-august-rev-2-part-43.stl:
  hash: 5f64b5602eef35b1f1ff07309beaca16585ef078
  links: []
  notes: []
tengu-august-rev-2-part-45.stl:
  hash: c04e6ef123e9d021579ac2703f57ca84e46436ab
  links: []
  notes: []
tengu-august-rev-2-part-50.stl:
  hash: a59662d430f55b63f66d381ad38968fda879a1d2
  links: []
  notes: []
tengu-august-rev-2-part-54.stl:
  hash: c6f4f80c4a25059ddd1337e7ada86db9c8c0de0e
  links: []
  notes: []
tengu-august-rev-2-part-56.stl:
  hash: 9ed5a19fc0360461b0e2f3dc3963d992d0874092
  links: []
  notes: []
tengu-august-rev-2-r-wing-1.stl:
  hash: bdc1a80658eca13fd7cbd3eeae54f59c34564657
  links: []
  notes: []
tengu-august-rev-2-r-wing-2-3.stl:
  hash: 321edc7972fd0ba5d0178722385babe17a0157a3
  links: []
  notes: []
tengu-august-rev-2-r-wing-2-5.stl:
  hash: 41f5274f85eaa890a7d137529adbf7aed839ccb4
  links: []
  notes: []
tengu-august-rev-2-r-wing-vertical-tip.stl:
  hash: e89242601a6db2bc0920a450df74ad007ce2302a
  links: []
  notes: []
tengu-august-rev-2-wing-fuse-front.stl:
  hash: 833b7ae123f0e3dc8b834e97ba5d1d8f8358c185
  links: []
  notes: []
tengu-august-rev-2-wing-fuse-midfront-left.stl:
  hash: 86084192228f1ba4c84fef9334c45ff01ffafe07
  links: []
  notes: []
tengu-august-rev-2-wing-fuse-midfront.stl:
  hash: 8a105596a9467daa4073d1bfa0f497abcbbe458f
  links: []
  notes: []
tengu-august-rev-2-wing-fuse-rear-tip-left.stl:
  hash: b05d371be14f88105674149ecd847d9822664265
  links: []
  notes: []
tengu-august-rev-2-wing-fuse-rear-tip.stl:
  hash: 058dd8a0cdc2733f396938300b7720c258dd7a87
  links: []
  notes: []
tengu-august-rev-2-wing-fuse-servo-bay-left.stl:
  hash: 98b4b2d0406eb495bcdf3c4941739dce5816ca3b
  links: []
  notes: []
tengu-august-rev-2-wing-fuse-servo-bay.stl:
  hash: 1a2bf9246def5e152db55dcf606ddc6afea0719b
  links: []
  notes: []
