Fiber-Fighter-Fiber-Fighter-Battery-Plate.stl:
  hash: b9a84d64a27f59ad06cfb5be6cc35176f6d8ab48
  links: []
  notes: []
Fiber-Fighter-Fiber-Fighter-Body.stl:
  hash: 1bcdd1abd9027817cda1b77756bb307d94576f7f
  links: []
  notes: []
Fiber-Fighter-Fiber-Fighter-Canopy.stl:
  hash: 751a04c1a72d5a09ab0bd48f9ada5aa3c62b87bd
  links: []
  notes: []
