arduino-mega-due-adapter-plate_lower_mount.stl:
  hash: 82ccfe94bfd65a7e6e1a1fb78118021a33b8bf53
  links: []
  notes: []
arduino-mega-due-adapter-plate_upper_mount.stl:
  hash: a046305e658fe6c70a46ff42caaf7bac73ae632d
  links: []
  notes: []
iPhone-6-6S-and-6-plus-Amp-Dock-files-iPhone-6-Amp-Dock.gco:
  analysis:
    dimensions:
      depth: 62.91099999999999
      height: 61.2
      width: 90.39800000000001
    estimatedPrintTime: 39258.81582201011
    filament:
      tool0:
        length: 26886.14998996804
        volume: 64.66876927028198
    printingArea:
      maxX: 145.199
      maxY: 131.771
      maxZ: 61.5
      minX: 54.801
      minY: 68.86
      minZ: 0.3
  hash: f6c24d67406658007c5b2d5c14506395a56bf584
  links:
  - hash: 411c0a9a351017fa5ed27ef882ec547fde339926
    name: iPhone-6-6S-and-6-plus-Amp-Dock-files-iPhone-6-Amp-Dock.stl
    rel: model
iPhone-6-6S-and-6-plus-Amp-Dock-files-iPhone-6-Amp-Dock.stl:
  hash: 411c0a9a351017fa5ed27ef882ec547fde339926
  links:
  - hash: f6c24d67406658007c5b2d5c14506395a56bf584
    name: iPhone-6-6S-and-6-plus-Amp-Dock-files-iPhone-6-Amp-Dock.gco
    rel: machinecode
  notes: []
iPhone-6-6S-and-6-plus-Amp-Dock-files-iPhone-6-Plus-Amp-Dock.stl:
  hash: 19e9da68235df44fc36548dc8cb6792012f2e4f4
  links: []
  notes: []
iphone-6-dock-stand-1.stl:
  hash: dfb28f6cfa0015cadfe383de46d2d01b5a4af60b
  links: []
  notes: []
rev2-awesome-iphone-holder-1.stl:
  hash: f73ace18c2510496b9514d08e913c24df4070c34
  links: []
  notes: []
