Bearing_Support.stl:
  hash: 432cea180b5e53dc81dd7db130c01bea3c7c50d6
  links: []
  notes: []
Spoolholder_i3_Frame_Support.stl:
  hash: 9400bce032222eca0d6bba0a887432e4251f463b
  links: []
  notes: []
