CableChainx4.stl:
  hash: 554414a2db489809505ce9b341f12a002fd31aee
  links: []
  notes: []
Cable_Chain_Carriage.STL:
  hash: 9cccd6baa526ed3941192c7df4c365e44c72b9d5
  links: []
  notes: []
Cable_Chain_Stepper.STL:
  hash: 58fa9cb2fc3fe94b8f9451b03bece8bc3e2a3fc9
  links: []
  notes: []
