Drogerdy-Raspberry-Pi-Controlled-Tank-Bot-CogBracketInner.stl:
  hash: 6be69c2af5b400966e7d12edb6b75e30ec4ba9ba
  links: []
  notes: []
Drogerdy-Raspberry-Pi-Controlled-Tank-Bot-CogBracketOuter.stl:
  hash: 7862895d16c189f86bdd05388b99043fa0be3f07
  links: []
  notes: []
Drogerdy-Raspberry-Pi-Controlled-Tank-Bot-Track.stl:
  hash: 301fd55926abae891fbbfc9de65b0deb3a5fbf5f
  links: []
  notes: []
Drogerdy-Raspberry-Pi-Controlled-Tank-Bot-body.stl:
  hash: 5508ab7109b0806c23f9de883605a5f52103a56a
  links: []
  notes: []
Drogerdy-Raspberry-Pi-Controlled-Tank-Bot-cog.stl:
  hash: 09ed32b74a240aa8d3c6d74b60aeb964773b31a6
  links: []
  notes: []
Drogerdy-Raspberry-Pi-Controlled-Tank-Bot-trackMidFrame.stl:
  hash: 56b988f85dd29d81c4b4b199d6c90c1b28f3aeac
  links: []
  notes: []
